language: emacs-lisp

env:
  global:
    - CASK=$HOME/.cask/bin/cask

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs24
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

install:
  - $CASK install

script:
  - $CASK exec ert-runner
